name: CouchbaseDemo
options:
  bundleIdPrefix: com.molo17
  groupSortPosition: top
  generateEmptyDirectories: true
targets:
  CouchbaseDemo:
    type: application
    platform: iOS
    deploymentTarget: "12.1"
    sources: [CouchbaseDemo]
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
